Add `--iree-hal-list-target-backends` flag. (#10629)
The HAL target backends are registered outside of the typical flags
system, so `--help` output just appears as
```
--iree-hal-target-backends=<string>                          - Target backends for executable compilation.
```

This adds a new flag with sample usage:

```
λ iree-compile.exe --iree-hal-list-target-backends
Registered target backends:
  cuda
  llvm-cpu
  metal
  metal-spirv
  vmvx
  vmvx-inline
  vulkan
  vulkan-spirv
  webgpu
  webgpu-wgsl
```

Part of addressing https://github.com/iree-org/iree/issues/10432

---

I think we should also plumb something similar through to the Python
bindings. This is what we have today:

```python
# Omit `target_backends`:
_ = compile_str(asm)

ValueError: Expected a non-empty list for 'target_backends'

# Try a backend that does not exist:
_ = compile_str(asm, target_backends=["unknown"])

CompilerToolError: Error invoking IREE compiler tool iree-compile
Diagnostics:
<stdin>:2:3: error: target backend 'unknown' not registered; registered backends: cuda, llvm-cpu, metal, metal, vmvx, vmvx-inline, vulkan, vulkan
  module @arithmetic {
  ^
compilation failed

# See a runtime helper method that we could model this after:
ireert.query_available_drivers()

['cuda', 'local-sync', 'local-task', 'vulkan']
```