[Codegen] Fix dominance issue in collapse shape fusion (#20864)
In fusion of consumer `tensor.collapse_shape` operations into
`scf.forall`, there is a potential dominance issue if the
`tensor.parallel_insert_slice` operation depends on both a BlockArgument
and an affine expression on the same BlockArgument (in this order). This
lead to the following error for the added test:
```
...
error: operand #1 does not dominate this use
    %2 = affine.apply #map(%arg4)
...
```

Signed-off-by: Jorn Tuyls <jorn.tuyls@gmail.com>