Revert "Convert TF models using TF Python API." (#12972)
Reverts openxla/iree#12758

This PR removes all of the TF models in our benchmarking suite. It also
introduces new failures when trying to re-add the TF models:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Exported function with exported name(s) 'model.__call__', 'model.keras_api.__call__' with multiple concrete functions. Add @tf.function(input_signature=[...]) on this function, or use a narrower list of exported names that excludes this function.
```