Pin nanobind to 1.9.2 to defer 2.0.0 API changes. (#17481)
Version 2.0.0 just landed a few minutes ago:
https://pypi.org/project/nanobind/#history, which broke some of our
builds:
https://github.com/iree-org/iree/actions/runs/9210086545/job/25336292024?pr=17478#step:4:14124

```
/work/runtime/bindings/python/hal.cc:1197:8: error: no member named 'def_static' in 'nanobind::enum_<iree_hal_element_types_t>'
      .def_static("map_to_dtype",
       ^
```