Avoid complaints about missing bc file if compiling for CUDA (#15232)
Previously this would throw errors like

```
ERROR: external/iree_cuda/BUILD:45:13: Executing genrule @iree_cuda//:libdevice_embedded__generator failed: missing input file 'external/iree_cuda/iree_local/libdevice.bc', owner: '@iree_cuda//:iree_local/libdevice.bc'
```

even though the CUDA build was not enabled. Use BUILD file as bc file as
... well its there and seems to work/it isn't used in anyway with CUDA
build disabled it just has to be something that exists.