Update WebGPU target using latest Tint code. (#10134)
Tested on a few programs, seems to still work: simple programs (no push
constants) compile to WGSL that looks reasonable and complex programs
(push constants) fail with errors like this:
```
Tint reported 1 error(s) for a SPIR-V program, see diagnostics:
error: unknown SPIR-V storage class: 9SPIR-V pointer type with ID 7 has invalid storage class 9
D:\dev\projects\iree/../iree-tmp/webgpu/unidirectional_lstm_webgpu_2022_08_18/\module__main_dispatch_0.mlir:2:2: error: failed to compile SPIR-V to WGSL. Consider inspecting the shader program using -iree-hal-dump-executable-intermediates.
  hal.executable.variant public @webgpu_wgsl_fb, target = <"webgpu", "webgpu-wgsl-fb", {spv.target_env = #spv.target_env<#spv.vce<v1.0, [Shader], [SPV_KHR_storage_buffer_storage_class]>, #spv.resource_limits<>>}> {
 ^
D:\dev\projects\iree/../iree-tmp/webgpu/unidirectional_lstm_webgpu_2022_08_18/\module__main_dispatch_0.mlir:2:2: note: see current operation: "hal.executable.variant"() ({
...
```

I want to route those diagnostics to MLIR and add line breaks at some
point (that will really help output legibility when the compiler runs
multithreaded)

---

This also adds a few compiler lit tests ~and enables building and
running those tests on our CI (`build_all` and `test_all`)~. As
compatibility issues are fixed, some of those lit tests will be removed
or adjusted. At that point I plan to enable the rest of our test suite,
similar to how Wasm is tested:
https://github.com/iree-org/iree/blob/a98f8ca3def0476efac60ecd171f9b201b3d7856/tests/e2e/xla_ops/BUILD#L393-L402