[WebGPU] Push constants Storage i32 -> Uniform vector<4xi32>. (#11392)
We discussed this [here on
Discord](https://discord.com/channels/689900678990135345/867052513935753277/1047198677514600518).

When using `tensor<Nxi32>` we get an error like this from Tint:
```
Tint reported 1 error(s) for a SPIR-V program, see diagnostics:
error: line:36: Structure id 8 decorated as Block for variable in
  Uniform storage class must follow relaxed uniform buffer layout rules:
  member 0 contains an array with stride 4 not satisfying alignment to 16
```

Following the spec:
https://www.w3.org/TR/WGSL/#address-space-layout-constraints, we should
be aligning to 16. Switching to `tensor<Nxvector<4xi32>>` gives us that
alignment.

This change packs a conceptual array of `i32`s into an array of
`vector<4xi32>`s - possibly with unused elements at the end. Unpacking
changes from using just `tensor::ExtractOp` to using `tensor::ExtractOp`
(to get one of the vec4s) -> `vector::ExtractElementOp` (to get the
specific element).