Revert "Add WebGPU compilation tests for xla_ops/ and tosa_ops/." (#10918)
Reverts iree-org/iree#10909

That change broke the `iree-test-android` CI pipeline:
https://buildkite.com/iree/iree-test-android/builds/7461#0184155a-9dca-4f64-8010-660f07d0b12a

```
[2022-10-26T17:52:28Z] cd /usr/src/github/iree/build-android/tests/e2e/tosa_ops && /usr/src/github/iree/build-android/../build-host/install/bin/iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=webgpu --iree-input-type=tosa /usr/src/github/iree/tests/e2e/tosa_ops/bitwise_or.mlir -o check_webgpu_bitwise_or.mlir_module.vmfb
--
  | [2022-10-26T17:52:28Z] /usr/src/github/iree/tests/e2e/tosa_ops/bitwise_or.mlir:0:0: error: target backend 'webgpu' not registered; registered backends: llvm-cpu, metal, metal, vmvx, vmvx-inline, vulkan, vulkan
  | [2022-10-26T17:52:28Z] compilation failed
```